// <auto-generated />
namespace _30Code.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Banco30Code : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Banco30Code));
        
        string IMigrationMetadata.Id
        {
            get { return "202010302128074_Banco30Code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
